### ISSUE TITLE
footer - entered items in menu box 1 and 2 - got error code

### ISSUE THREAD

**Issue by mwllr** [web-illinois/illinois_framework_theme#13]
got an error code when entering some. they entered, but got the code. 
![Screen Shot 2021-02-17 at 5 34 06 PM](https://user-images.githubusercontent.com/54747669/108288085-96218180-7151-11eb-8053-d349655da32c.png)

**Comment by wrg20** [comment]
The offending module was something I was trying out.  I have uninstalled it from the website.  The error should now go away now.  The module requires more development to be useful.
