### ISSUE TITLE
Split Feature Paragraph

### ISSUE THREAD

**Issue by wrg20** [web-illinois/illinois_framework_theme#36]
![image](https://user-images.githubusercontent.com/1544079/110497666-497bf700-80bc-11eb-85f1-72ce32f0531c.png)

**Comment by lizshalley** [comment]
looks good!

**Comment by wrg20** [comment]
Split Feature Complete.

**Comment by mwllr** [comment]
Add field for spacing before paragraph: no, small, med, lg, xlg..
See Call to Action Narrow for example already added.

**Comment by lizshalley** [comment]
- [ ] all headlines and body copy should be white on orange and blue, and orange and blue gradient backgrounds.
- [ ] body copy should be white on orange background
- [ ] tablet/mobile, can buttons be same width when they stack?

![Test - Feature Split  Animal Sciences  University of Illinois-1](https://user-images.githubusercontent.com/8646013/124161739-64a3b580-da63-11eb-9b5f-68b12a5027ad.jpeg)

**Comment by mwllr** [comment]
TESTING (if you can give example page and screen shots, please do so!):
Share your feedback in a new comment and check off the part you have done in this comment:
- [ ] Usability - front end (how does this behave/display?)
- [ ] Usability - back end (intuitive? easy/hard to use?)
- [ ] Accessibility - (FAE site/run on pages with these paragraph types)

Browser Testing (Please be descriptive in browsers you tested on platform and version #.)
- [ ] Mobile - iphone
- [ ] Mobile - android
- [ ] Edge 
- [ ] Safari
- [ ] Chrome
- [ ] Firefox

**Comment by mwllr** [comment]
margin/padding between main title and paragraph should match the main formatting for h2 and p.
Change title font size to match h2 - 35px
https://cdn.brand.illinois.edu/toolkit/dev/examples/stylesheets/formatting/index.html
![Screen Shot 2021-08-10 at 12 20 43 PM](https://user-images.githubusercontent.com/54747669/128905753-b08a385c-103d-4d8f-a7a5-6db83d388b4d.png)
